# Generated by Django 4.2.1 on 2023-05-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('about', models.TextField()),
                ('character', models.TextField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='UnitPh/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techMarket.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='gr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techMarket.group'),
        ),
    ]
