# Generated by Django 4.2.1 on 2023-05-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techMarket', '0002_backet'),
    ]

    operations = [
        migrations.AddField(
            model_name='backet',
            name='l',
            field=models.IntegerField(default=0),
        ),
    ]
